version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: remittance
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: 8080
      DATABASE_URL: postgres://app:app@postgres:5432/remittance
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  db_data: